INSERT INTO public.opportunities (
  title, slug, category, organization, location, country, level, summary, description, eligibility, benefits, "applicationProcess", deadline, "applicationLink", featured, trending, image, "imageHint", tags, status, "metaTitle", "metaDescription"
) VALUES
(
  'Google Software Engineering Internship',
  'google-software-engineering-internship',
  'Internships',
  'Google',
  'Mountain View, CA',
  'USA',
  'Undergraduate',
  'Join Google for a 12-week paid internship to work on impactful projects.',
  'The Software Engineering Internship program is a 12-14 week internship for students. Interns will work on a specific project critical to Google’s needs. We offer a variety of projects in areas such as software development, site reliability, and machine learning.',
  ARRAY['Currently pursuing a BS, MS or PhD in computer science or a related technical field.', 'Experience in software development in one or more general-purpose programming languages.', 'Must be returning to a degree program after the internship ends.'],
  ARRAY['Competitive salary', 'Housing stipend', 'Relocation assistance', 'Health benefits', 'Professional development opportunities'],
  'Apply online through the Google Careers portal. The process includes a resume screen, a technical phone interview, and a series of onsite interviews.',
  '2024-12-15T23:59:59Z',
  '#',
  true,
  true,
  'https://picsum.photos/seed/1/600/400',
  'tech office',
  ARRAY['Software Engineering', 'Internship', 'Google', 'USA', 'Tech'],
  'published',
  'Google Software Engineering Internship | Jobsyde',
  'Apply for the Google Software Engineering Internship. A 12-week paid internship for students to work on impactful projects in software development and more.'
),
(
  'Rhodes Scholarship at Oxford University',
  'rhodes-scholarship-at-oxford-university',
  'Scholarships',
  'University of Oxford',
  'Oxford',
  'UK',
  'Postgraduate',
  'A prestigious postgraduate award supporting exceptional students from around the world to study at the University of Oxford.',
  'The Rhodes Scholarship is a life-changing opportunity to join a talented, diverse, and motivated community of scholars at Oxford. The scholarship covers all University and College fees, a personal stipend, and one economy class airfare to Oxford at the start of the scholarship and one economy class airfare back to the student''s home country at the conclusion of the scholarship.',
  ARRAY['Citizen of a Rhodes-eligible country.', 'Must have completed a Bachelor''s degree to a high standard.', 'Specific age requirements apply.'],
  ARRAY['Full tuition fees covered', 'Annual stipend (£18,180 per annum for 2023-24)', 'Two return flights to the UK'],
  'Applications are made online. Required documents include an academic statement, a personal statement, and letters of recommendation. Shortlisted candidates are invited for an interview.',
  '2024-10-31T23:59:59Z',
  '#',
  true,
  false,
  'https://picsum.photos/seed/2/600/400',
  'university campus',
  ARRAY['Scholarship', 'Postgraduate', 'Oxford University', 'UK', 'Academia'],
  'published',
  'Rhodes Scholarship at Oxford University | Jobsyde',
  'Apply for the prestigious Rhodes Scholarship to study at the University of Oxford. A postgraduate award for exceptional students worldwide.'
),
(
  'Data Scientist at Meta',
  'data-scientist-at-meta',
  'Jobs',
  'Meta',
  'Menlo Park, CA',
  'USA',
  'Professional',
  'Meta is seeking an experienced Data Scientist to join our product analytics team.',
  'As a Data Scientist, you will be responsible for leading data-driven initiatives. You will work on a major project and collaborate with a team of engineers, product managers, and other data scientists to drive product strategy.',
  ARRAY['PhD, or MS/BS in a quantitative field (e.g., Computer Science, Engineering, Statistics).', '4+ years of experience in data science or analytics.', 'Proficiency in SQL, Python or R.'],
  ARRAY['Competitive salary and bonus', 'Comprehensive health benefits', 'Stock options', 'Generous parental leave'],
  'Submit your resume and cover letter through the Meta Careers portal. The interview process includes a technical screening, a data challenge, and several rounds of onsite interviews.',
  '2025-01-31T23:59:59Z',
  '#',
  false,
  true,
  'https://picsum.photos/seed/3/600/400',
  'data visualization',
  ARRAY['Data Science', 'Jobs', 'Meta', 'USA', 'Professional'],
  'published',
  'Data Scientist at Meta | Jobsyde',
  'Join Meta as an experienced Data Scientist. Lead data-driven initiatives and drive product strategy in Menlo Park, CA.'
),
(
  'Fulbright Foreign Student Program',
  'fulbright-foreign-student-program',
  'Fellowships',
  'U.S. Department of State',
  'Various Universities',
  'USA',
  'Graduate',
  'Enables graduate students, young professionals and artists from abroad to study and conduct research in the United States.',
  'The Fulbright Foreign Student Program enables graduate students, young professionals, and artists from abroad to research and study in the United States for one year or longer at U.S. universities or other appropriate institutions. The program operates in more than 160 countries worldwide.',
  ARRAY['Country-specific eligibility requirements apply.', 'Typically requires a completed undergraduate degree.', 'Proficiency in English.'],
  ARRAY['Tuition and fees', 'A living stipend', 'Health insurance', 'Travel allowance'],
  'All Foreign Student Program applications are processed by bi-national Fulbright Commissions/Foundations or U.S. Embassies. Therefore, foreign students must apply through the Fulbright Commission/Foundation or U.S. Embassy in their home countries.',
  '2024-11-01T23:59:59Z',
  '#',
  false,
  true,
  'https://picsum.photos/seed/4/600/400',
  'diverse students',
  ARRAY['Fellowship', 'Graduate', 'Research', 'USA', 'International'],
  'published',
  'Fulbright Foreign Student Program in the USA | Jobsyde',
  'Study and conduct research in the United States with the Fulbright Foreign Student Program for graduate students and young professionals.'
),
(
  'National Geographic Early Career Grant',
  'national-geographic-early-career-grant',
  'Grants',
  'National Geographic Society',
  'Worldwide',
  'Global',
  'All Levels',
  'The National Geographic Early Career Grant is designed to offer less experienced individuals an opportunity to lead a project.',
  'Early Career Grants are designed to offer less experienced individuals an opportunity to lead a project. Grant-funded projects should be bold, innovative, and transformative. All proposed projects must be in alignment with one of the National Geographic Society’s three focus areas: The Human Journey, Wildlife and Wild Places, and Our Changing Planet.',
  ARRAY['No advanced degrees are required.', 'Applicants must be at least 18 years old.', 'Project must align with National Geographic''s focus areas.'],
  ARRAY['Funding ranging from $5,000 to $10,000', 'Networking opportunities', 'Support from the National Geographic Society'],
  'Proposals are submitted online via the National Geographic grants portal. The application includes a project description, budget, and timeline.',
  '2024-12-31T23:59:59Z',
  '#',
  true,
  false,
  'https://picsum.photos/seed/5/600/400',
  'wildlife photography',
  ARRAY['Grant', 'Early Career', 'Research', 'Conservation', 'Global'],
  'published',
  'National Geographic Early Career Grant | Jobsyde',
  'Lead a bold and innovative project with funding from the National Geographic Early Career Grant. Open to less experienced individuals worldwide.'
),
(
  'Effective Communication in the Workplace',
  'effective-communication-in-the-workplace',
  'Career Advice',
  'Jobsyde',
  'Online',
  'Global',
  'All Levels',
  'Learn how to communicate effectively to build stronger professional relationships and advance your career.',
  'This article provides a comprehensive guide to mastering communication in a professional setting. Topics covered include active listening, non-verbal communication, clarity and conciseness, providing feedback, and navigating difficult conversations. Real-world examples and actionable tips are provided to help you improve your communication skills.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  '',
  '2029-12-31T23:59:59Z',
  '',
  false,
  false,
  'https://picsum.photos/seed/6/600/400',
  'team meeting',
  ARRAY['Career Advice', 'Soft Skills', 'Communication', 'Professional Development'],
  'published',
  'Effective Communication in the Workplace | Jobsyde',
  'Master workplace communication with our guide on active listening, feedback, and navigating difficult conversations to advance your career.'
),
(
  'Study in Australia: A Comprehensive Guide',
  'study-in-australia-a-comprehensive-guide',
  'Study Abroad',
  'International Student Hub',
  'Australia',
  'Australia',
  'All Levels',
  'Everything you need to know about studying in Australia, from university selection to visa applications.',
  'This guide covers all aspects of studying in Australia. It provides information on the Australian education system, top universities, popular courses, cost of living, student visa requirements, and scholarship opportunities. It also includes tips for adapting to life in Australia.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  '',
  '2029-12-31T23:59:59Z',
  '',
  false,
  false,
  'https://picsum.photos/seed/7/600/400',
  'Sydney opera',
  ARRAY['Study Abroad', 'Australia', 'Education', 'Student Guide'],
  'published',
  'Study in Australia: A Comprehensive Guide | Jobsyde',
  'Your complete guide to studying in Australia. Learn about universities, visas, scholarships, and student life down under.'
),
(
  'Marketing Internship at HubSpot',
  'marketing-internship-at-hubspot',
  'Internships',
  'HubSpot',
  'Dublin',
  'Ireland',
  'Undergraduate',
  'Join HubSpot''s marketing team for a summer internship and gain hands-on experience in inbound marketing.',
  'As a Marketing Intern, you will be involved in content creation, social media marketing, SEO, and data analysis. This is a great opportunity to learn from industry experts and contribute to real marketing campaigns.',
  ARRAY['Currently enrolled in a Bachelor''s degree in Marketing, Business, or a related field.', 'Strong written and verbal communication skills.', 'Familiarity with digital marketing concepts.'],
  ARRAY['Paid internship', 'Mentorship program', 'Free lunch and snacks', 'Opportunity for a full-time offer'],
  'Apply online with your resume and a cover letter. You may be asked to complete a short marketing challenge.',
  '2025-03-01T23:59:59Z',
  '#',
  false,
  true,
  'https://picsum.photos/seed/8/600/400',
  'marketing chart',
  ARRAY['Marketing', 'Internship', 'HubSpot', 'Ireland', 'Digital Marketing'],
  'published',
  'Marketing Internship at HubSpot in Dublin | Jobsyde',
  'Gain hands-on inbound marketing experience with a summer internship at HubSpot. Apply now for this undergraduate opportunity in Dublin.'
);
